### ISSUE TITLE
应用假死后，restart无法重启

### ISSUE THREAD

**Issue by Zziwen** [lework/script#1]
Action: restart Get cat1 ProcessInfo Error: [Errno 2] No such file or directory

**Comment by Zziwen** [comment]
![image](https://user-images.githubusercontent.com/46589682/71806105-ea2eeb00-30a2-11ea-9103-5c975342b74e.png)

**Comment by lework** [comment]
看错误应该是找不到进程信息，你看下`cat1` 是不是 supervisor 中配置的 program 名称

**Comment by Zziwen** [comment]
都是 cat1

cat1:
  type: HTTP
  mode: GET               # http动作：POST,GET 默认: GET
  host: 127.0.0.1         # 主机地址, 默认: localhost
  path: /                 # URI地址，默认: /
  port: 8181              # 检测端口，默认: 80
  periodSeconds: 10       # 检查的频率(以秒为单位), 默认: 5
  initialDelaySeconds: 10 # 首次检查等待的时间(以秒为单位), 默认: 1
  timeoutSeconds: 5       # 检查超时的秒数, 默认: 3
  failureThreshold: 3     # 检查成功后，最少连续检查失败多少次才被认定为失败, 默认: 3
  successThreshold: 2     # 失败后检查成功的最小连续成功次数, 默认：1
  action: restart         # 触发的动作: restart,email,wechat 默认: restart
[root@master ~]# cat /etc/supervisord.d/testpy.ini 
[program:cat1]
command=python -m SimpleHTTPServer 8181
process_name=%(program_name)s
numprocs=1

**Comment by lework** [comment]
哦，那就是没有连接上supervisor，你查看下socker地址是不是这个 `unix:///var/run/supervisor.sock` 或者接口配置对不对

**Comment by Zziwen** [comment]
谢谢，是这个问题，配置文件默认是/var/run/supervisor/supervisor.sock  ，我修改后可以成功了
[unix_http_server]
;file=/var/run/supervisor/supervisor.sock   ; (the path to the socket file)
file=/var/run/supervisor.sock   ; (the path to the socket file)

**Comment by lework** [comment]
嗯，这个错误是supervisor连接客户端报错的，你也可以在健康检查配置文件中配置supervisor的连接地址。
